[build]
  functions = "functions"
  publish = "dist"

[context.production]
  command = "npm run build && cd functions/node-fetch && npm install"

[context.development]
  command = "npm run build-dev"
