[build]
  functions = "functions"
  publish = "dist"

[context.production]
  command = "npm run build && cd functions/node-fetch && npm install"

[context.development]
  command = "npm run build-dev"

[dev] # config specific to `netlify dev`
  framework = "#custom"
  command = "npm run start-dev"
  targetPort = 3000
  port = 8888
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
