// app
export const HIDE_NAV = 'HIDE_NAV'
export const SELECT_PODCAST = 'SELECT_PODCAST'
export const SET_FILTER = 'SET_FILTER'
export const SET_NAV_EXPANDER = 'SET_NAV_EXPANDER'
export const SET_STARRED = 'SET_STARRED'
export const SET_THEME = 'SET_THEME'
export const SHOW_NAV = 'SHOW_NAV'
export const STAR_PODCAST = 'STAR_PODCAST'
export const UNSTAR_PODCAST = 'UNSTAR_PODCAST'

// audio
export const AUDIO_SEEKED = 'AUDIO_SEEKED'
export const FORWARD_AUDIO = 'FORWARD_AUDIO'
export const PAUSE_AUDIO = 'PAUSE_AUDIO'
export const PLAY_AUDIO = 'PLAY_AUDIO'
export const REPLAY_AUDIO = 'REPLAY_AUDIO'
export const SEEK_AUDIO = 'SEEK_AUDIO'
export const SELECT_AUDIO = 'SELECT_AUDIO'
export const SET_AUDIO_DURATION = 'SET_AUDIO_DURATION'
export const SET_AUDIO_POSITION = 'SET_AUDIO_POSITION'
