// this export pattern supports tree-shaking, and makes the downstream import simple

export { default as IcoDot } from './IcoDot'
export { default as IcoFastFwdStop } from './IcoFastFwdStop'
export { default as IcoForwardStop } from './IcoForwardStop'
export { default as IcoHome } from './IcoHome'
export { default as IcoLeft } from './IcoLeft'
export { default as IcoMagnifier } from './IcoMagnifier'
export { default as IcoMinus } from './IcoMinus'
export { default as IcoPause } from './IcoPause'
export { default as IcoPlay } from './IcoPlay'
export { default as IcoPlus } from './IcoPlus'
export { default as IcoRewindStop } from './IcoRewindStop'
export { default as IcoRight } from './IcoRight'
export { default as IcoSolidArrowDown } from './IcoSolidArrowDown'
export { default as IcoSolidArrowUp } from './IcoSolidArrowUp'
